<?php

$things = array(
    array("name"=>"kort", "weight"=>90, "value"=>150),
    array("name"=>"kompas", "weight"=>130, "value"=>35),
    array("name"=>"vand", "weight"=>1530, "value"=>200),
    array("name"=>"sandwich", "weight"=>500, "value"=>160),
    array("name"=>"sukker", "weight"=>150, "value"=>60),
    array("name"=>"daasemad", "weight"=>680, "value"=>45),
    array("name"=>"banan", "weight"=>270, "value"=>60),
    array("name"=>"aeble", "weight"=>390, "value"=>40),
    array("name"=>"ost", "weight"=>230, "value"=>30),
    array("name"=>"oel", "weight"=>520, "value"=>10),
    array("name"=>"solcreme", "weight"=>110, "value"=>110),
    array("name"=>"kamera", "weight"=>320, "value"=>30),
    array("name"=>"t-shirt", "weight"=>240, "value"=>15),
    array("name"=>"bukser", "weight"=>480, "value"=>10),
    array("name"=>"paraply", "weight"=>730, "value"=>40),
    array("name"=>"vandtaette-bukser", "weight"=>420, "value"=>70),
    array("name"=>"vandtaet-overtoej", "weight"=>430, "value"=>75),
    array("name"=>"pung", "weight"=>220, "value"=>80),
    array("name"=>"solbriler", "weight"=>70, "value"=>20),
    array("name"=>"haandklaede", "weight"=>180, "value"=>12),
    array("name"=>"sokker", "weight"=>40, "value"=>50),
    array("name"=>"bog", "weight"=>300, "value"=>10),
    array("name"=>"notesbog", "weight"=>900, "value"=>1),
    array("name"=>"telt", "weight"=>2000, "value"=>150),
);
